-- 创建数据库
CREATE DATABASE IF NOT EXISTS 01;

-- 使用数据库
USE 01;

-- 创建用户表
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 创建管理一的数据表
CREATE TABLE IF NOT EXISTS manage1 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    content1 VARCHAR(100) NOT NULL,
    content2 VARCHAR(100) NOT NULL,
    content3 VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 创建管理二的数据表
CREATE TABLE IF NOT EXISTS manage2 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    content1 VARCHAR(100) NOT NULL,
    content2 VARCHAR(100) NOT NULL,
    content3 VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 创建管理三的数据表
CREATE TABLE IF NOT EXISTS manage3 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    content1 VARCHAR(100) NOT NULL,
    content2 VARCHAR(100) NOT NULL,
    content3 VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 
